### PR TITLE
Added failing test for \ldots replacement

### PR DESCRIPTION
**Pull request by cebe**
Currently `...` is replaced with `\ldots`. This is fine but may cause problems if we have text like `try...catch`.

The `\ldots` should be covered in `{}` to avoid creating an undefined control sequence: `\ldotscatch`.

### CODE REVIEW

**Comment by mvriel** [comment]
Nice catch! Thank you for contributing

**Comment by cebe** [comment]
You're welcome, thanks for the library :)

Could you please tag a new version with this fix?

**Comment by mvriel** [comment]
Sure! I just tagged 1.0.1 :)

**Comment by cebe** [comment]
awesome :)

**Pull request merged**
