### PR TITLE
Fixed #3

### LINKED ISSUE #3: German quotes are broken
In german (and a few other languages) the correct way to display (double) quotes is such that the first quotes are on the bottom like this : ,,text" (I am using commas here, but it shouldn't be commas...) . This utility breaks that by replacing `"text"` by ``` ``text''``` and so the quotes are always on the top.

Suggested solution: replace `"text"` by `\enquote{text}`. This solution needs the csquotes package, but quotes are then automatically rendered correctly based on the language settings in the document (babel or polyglossia).

### PR DESCRIPTION
**Pull request by marekdedic**

### CODE REVIEW

**Comment by marekdedic** [comment]
The CI has failed but I don't fully understand the error message and don't think it's actually a problem with the code.

**Comment by cebe** [comment]
These changes could result in broken nesting of brackets in case quoting is not done correctly, which will result in the latex parser to fail.

**Comment by marekdedic** [comment]
Oh, that is true... Do you see any way to fix that? Unfortunatelly, I do not...

**Comment by cebe** [comment]
It is possible to fix that but that does not work with simple replace approach, some parsing of the original content is needed for that.

**Comment by mvriel** [comment]
I have updated master to keep the CI from failing; this was an issue introduced by a Travis worker and was fixed by removing a very specific version check, see: https://docs.travis-ci.com/user/languages/php/#PHP-installation

**Comment by mvriel** [comment]
Unfortunately it is quite hard to resolve those nesting things without writing far more complex statements or even changing this component to a more sophisticated parser that first tokenizes the given string. (See the concept of "Pushdown Automatons" when dealing with parsing nested structures).

I must admit that I am not aware of how the double backtick notation works, @GenaBitu: can you tell me what type of fix this is? Is this broken? Broken for a few Latex versions? Or is this more cosmetic and 'correct' Latex usage?

If the current implementation is really really broken and this new version is only broken when a syntax error occurs then it may be worth considering merging this anyway since it is an improvement on the existing situation.

**Comment by cebe** [comment]
As far as I see, the current solution is fail save, i.e. will not break on wrong syntax but only works for english. With the fix it works for other languages but may create wrong syntax that will stop the latex parser from rendering the file.

**Comment by mvriel** [comment]
I also noticed that the command used in this PR is only available in a non-default package. So we should then include the correct usepackage command as well. 

I think I would feel a little bit more comfortable having this as an option rather than a default due to the extra package that is introduced and the behaviour that can break. Adding a new non-default package to be supported also feels like a BC break because I cannot predict if all the consumers of this library have this package?

> Do let me know if you think I am too cautious; I am not fully intimate with how many package Latex includes per distro

I also think that a FAQ entry in the README is also nice since I can see how this can raise flags.

**Comment by marekdedic** [comment]
As far as I know, csquotes is part of standard installation of TeX Live. It doesn't come preinstalled with MikTeX, but is installed automatically upon using (as are almost all packages in MikTeX). It also works out of the box with both XeTeX and LuaTeX. So I think it shouldn't be a BC problem unless someone is using locally built LaTeX with this package excluded (you decide whether that's a problem, I wouldn't mind it).

I think the nesting problem could be detected (albeit not in a nice way) by counting brackets inside the qoutes (number of `{` should tally with the number of `}`). I don't, however, see how to fix such a problem if it is detected.

Unfortunately, I don't see any other solution that wouldn't break quotes in English.

This issue is definitely more on the 'cosmetic' side of things.

**Comment by cebe** [comment]
the BC break occurs on the level of existing documents that need to be adjusted by adding a `\usepackage{...}` to work with the new code.

**Pull request closed without merging**
